ALTER TABLE `gamingsa_wanton_test`.`wod_characters` 
DROP COLUMN `Next_Power_Stat_Increase`,
DROP COLUMN `Hours_On`,
DROP COLUMN `Potential_Experience`,
DROP COLUMN `Updated_PP`,
DROP COLUMN `Granted_XP`,
DROP COLUMN `Logged_Today`,
DROP COLUMN `Last_Scene_Date`,
DROP COLUMN `Cell_ID`,
DROP COLUMN `Login_Note`,
DROP COLUMN `When_Last_Asst_ST_Updated`,
DROP COLUMN `Last_Asst_ST_Updated`,
DROP COLUMN `Last_Login`,
DROP COLUMN `First_Login`,
DROP COLUMN `XP_Per_Day`,
CHANGE COLUMN `When_Last_ST_Updated` `updated_by_id` INT NULL ,
CHANGE COLUMN `Last_ST_Updated` `updated_on` datetime null,
CHANGE COLUMN `Character_ID` `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `Primary_Login_ID` `user_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Character_Name` `character_name` VARCHAR(45) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Show_Sheet` `show_sheet` ENUM('Y','N') NOT NULL DEFAULT 'N' ,
CHANGE COLUMN `View_Password` `view_password` VARCHAR(30) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Character_Type` `character_type` VARCHAR(15) NOT NULL DEFAULT '' ,
CHANGE COLUMN `City` `city` VARCHAR(15) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Age` `age` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Sex` `sex` ENUM('Male','Female','Other') NOT NULL DEFAULT 'Male' ,
CHANGE COLUMN `Apparent_Age` `apparent_age` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Concept` `concept` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Description` `description` TEXT NOT NULL ,
CHANGE COLUMN `URL` `url` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Safe_Place` `safe_place` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Friends` `friends` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Exit_Line` `exit_line` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Icon` `icon` VARCHAR(100) NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Is_NPC` `is_npc` ENUM('Y','N') NOT NULL DEFAULT 'N' ,
CHANGE COLUMN `Virtue` `virtue` VARCHAR(15) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Vice` `vice` VARCHAR(15) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Splat1` `splat1` VARCHAR(20) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Splat2` `splat2` VARCHAR(30) NOT NULL DEFAULT '' ,
CHANGE COLUMN `SubSplat` `subsplat` VARCHAR(40) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Size` `size` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Speed` `speed` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Initiative_Mod` `initiative_mod` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Defense` `defense` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Armor` `armor` VARCHAR(5) NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Health` `health` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Wounds_Agg` `wounds_agg` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Wounds_Lethal` `wounds_lethal` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Wounds_Bashing` `wounds_bashing` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Willpower_Perm` `willpower_perm` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Willpower_Temp` `willpower_temp` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Power_Stat` `power_stat` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Power_Points` `power_points` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Morality` `morality` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' ,
CHANGE COLUMN `Merits` `merits` TEXT NOT NULL ,
CHANGE COLUMN `Flaws` `flaws` TEXT NOT NULL ,
CHANGE COLUMN `Powers` `powers` TEXT NOT NULL ,
CHANGE COLUMN `Equipment_Public` `equipment_public` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Equipment_Hidden` `equipment_hidden` TEXT NOT NULL ,
CHANGE COLUMN `Public_Effects` `public_effects` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `History` `history` TEXT NOT NULL ,
CHANGE COLUMN `Character_Notes` `character_notes` TEXT NOT NULL ,
CHANGE COLUMN `Goals` `goals` TEXT NOT NULL ,
CHANGE COLUMN `Head_Sanctioned` `head_sanctioned` ENUM('Y','N','') NOT NULL DEFAULT 'Y' ,
CHANGE COLUMN `Is_Sanctioned` `is_sanctioned` ENUM('Y','N','') NOT NULL DEFAULT 'Y' ,
CHANGE COLUMN `Asst_Sanctioned` `asst_sanctioned` ENUM('Y','N','') NOT NULL DEFAULT 'Y' ,
CHANGE COLUMN `Is_Deleted` `is_deleted` ENUM('Y','N') NOT NULL DEFAULT 'N' ,
CHANGE COLUMN `Current_Experience` `current_experience` FLOAT(6,2) NOT NULL DEFAULT '0.00' ,
CHANGE COLUMN `Total_Experience` `total_experience` FLOAT(6,2) NOT NULL DEFAULT '0.00' ,
CHANGE COLUMN `GM_Notes` `gm_notes` TEXT NOT NULL ,
CHANGE COLUMN `Sheet_Update` `sheet_update` TEXT NOT NULL ,
CHANGE COLUMN `Hide_Icon` `hide_icon` ENUM('Y','N') NOT NULL DEFAULT 'N' ,
CHANGE COLUMN `Helper` `helper` VARCHAR(255) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Status` `status` VARCHAR(25) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Bonus_Attribute` `bonus_attribute` VARCHAR(20) NOT NULL DEFAULT '' ,
CHANGE COLUMN `Misc_Powers` `misc_powers` TEXT NOT NULL ,
CHANGE COLUMN `Average_Power_Points` `average_power_points` DECIMAL(4,2) NOT NULL DEFAULT '0.00' ,
CHANGE COLUMN `Power_Points_Modifier` `power_points_modifier` DECIMAL(4,2) NOT NULL DEFAULT '0.00' ,
CHANGE COLUMN `Temporary_Health_Levels` `temporary_health_levels` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `gamingsa_wanton_test`.`wod_characters` 
RENAME TO  `gamingsa_wanton_test`.`characters` ;

ALTER TABLE `gamingsa_wanton_test`.`wod_characters_powers` 
DROP COLUMN `UDF1`,
CHANGE COLUMN `CharacterID` `character_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `id`,
CHANGE COLUMN `PowerID` `id` INT(10) UNSIGNED NOT NULL ,
CHANGE COLUMN `PowerType` `power_type` VARCHAR(45) NOT NULL DEFAULT '' ,
CHANGE COLUMN `PowerName` `power_name` VARCHAR(45) NOT NULL DEFAULT '' ,
CHANGE COLUMN `PowerNote` `power_note` VARCHAR(45) NOT NULL DEFAULT '' ,
CHANGE COLUMN `PowerLevel` `power_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' , RENAME TO  `gamingsa_wanton_test`.`character_powers` ;

delete from `gamingsa_wanton_test`.`character_powers` WHERE `id` = 0;
ALTER TABLE `gamingsa_wanton_test`.`character_powers` 
CHANGE COLUMN `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT ;


ALTER TABLE `gamingsa_wanton_test`.`characters` 
DROP COLUMN `Subterfuge_Spec`,
DROP COLUMN `Subterfuge`,
DROP COLUMN `Streetwise_Spec`,
DROP COLUMN `Streetwise`,
DROP COLUMN `Socialize_Spec`,
DROP COLUMN `Socialize`,
DROP COLUMN `Persuasion_Spec`,
DROP COLUMN `Persuasion`,
DROP COLUMN `Intimidation_Spec`,
DROP COLUMN `Intimidation`,
DROP COLUMN `Expression_Spec`,
DROP COLUMN `Expression`,
DROP COLUMN `Empathy_Spec`,
DROP COLUMN `Empathy`,
DROP COLUMN `Animal_Ken_Spec`,
DROP COLUMN `Animal_Ken`,
DROP COLUMN `Weaponry_Spec`,
DROP COLUMN `Weaponry`,
DROP COLUMN `Survival_Spec`,
DROP COLUMN `Survival`,
DROP COLUMN `Stealth_Spec`,
DROP COLUMN `Stealth`,
DROP COLUMN `Larceny_Spec`,
DROP COLUMN `Larceny`,
DROP COLUMN `Firearms_Spec`,
DROP COLUMN `Firearms`,
DROP COLUMN `Drive_Spec`,
DROP COLUMN `Drive`,
DROP COLUMN `Brawl_Spec`,
DROP COLUMN `Brawl`,
DROP COLUMN `Athletics_Spec`,
DROP COLUMN `Athletics`,
DROP COLUMN `Science_Spec`,
DROP COLUMN `Science`,
DROP COLUMN `Politics_Spec`,
DROP COLUMN `Politics`,
DROP COLUMN `Occult_Spec`,
DROP COLUMN `Occult`,
DROP COLUMN `Medicine_Spec`,
DROP COLUMN `Medicine`,
DROP COLUMN `Investigation_Spec`,
DROP COLUMN `Investigation`,
DROP COLUMN `Crafts_Spec`,
DROP COLUMN `Crafts`,
DROP COLUMN `Computer_Spec`,
DROP COLUMN `Computer`,
DROP COLUMN `Academics_Spec`,
DROP COLUMN `Academics`,
DROP COLUMN `Composure`,
DROP COLUMN `Manipulation`,
DROP COLUMN `Presence`,
DROP COLUMN `Stamina`,
DROP COLUMN `Dexterity`,
DROP COLUMN `Strength`,
DROP COLUMN `Resolve`,
DROP COLUMN `Wits`,
DROP COLUMN `Intelligence`;
