CREATE TABLE `plots` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `plot_name` varchar(100) NOT NULL DEFAULT '',
  `Site_ID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Submitter_ID` int(10) unsigned NOT NULL DEFAULT '0',
  `Submitted_Date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Start_Date` date NOT NULL DEFAULT '0000-00-00',
  `End_Date` date NOT NULL DEFAULT '0000-00-00',
  `Plot_Category` enum('One-Shot','Adventure','Setting','Metaplot','C/F/S') NOT NULL DEFAULT 'One-Shot',
  `Synopsis` varchar(255) NOT NULL DEFAULT '',
  `Public_Information` varchar(255) NOT NULL DEFAULT '',
  `Description` text NOT NULL,
  `Result` text NOT NULL,
  `Notes` text NOT NULL,
  `Status` enum('Pending','In Progress','Suspended','Completed','Was Used','Denied','Deleted') NOT NULL DEFAULT 'Pending',
  `May_Post` enum('Y','N') DEFAULT 'N',
  `Approver_ID` int(10) unsigned NOT NULL DEFAULT '0',
  `Approved_Date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `Thread_ID` mediumint(8) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`Plot_ID`),
  KEY `Submitted_Date` (`Submitted_Date`),
  KEY `Start_Date` (`Start_Date`),
  KEY `Status` (`Status`),
  KEY `Plot_Name` (`Plot_Name`),
  KEY `Submitter_ID` (`Submitter_ID`),
  KEY `Plot_Category` (`Plot_Category`),
  KEY `End_Date` (`End_Date`)
) ENGINE=InnoDB AUTO_INCREMENT=141 DEFAULT CHARSET=utf8